### PR TITLE
Issue template and Pull Request template added

### PR DESCRIPTION
**Pull request by daguttierrez**
### Description
- Issue template has been added to the project
- Pull request template has been added to the project

Additional Info: https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by nikitaeverywhere** [comment]
Hi Diego! :) Thanks for finding [a motivation](https://hacktoberfest.digitalocean.com) to contribute to my project, I really appreciate this!

Usually PR/Issue templates are very specific from one project to another, and I think this case is not an exception. The templates you uploaded seem to be copied from somewhere, at least at the first glance.

There are a couple of things in your templates which I would consider to re-think:

Issue template
1. OS version -> Browser version
2. What's Butter in about tab?
3. Screenshots can be mentioned without a link to a specific software/service which do screenshots.

PR template
1. I think Migrations is odd.
2. Related PRs/branches almost never happen as well, the project is not so big. Those who work "on big parts" already know how to design a PR descriptions.
3. Todos, as well, odd here. No one will accept PRs that add more work.
4. Impacted areas are always obvious.
5. No `/CONTRIBUTING.md`, but the link to file exists.

And I think writing a lot of requirements usually repels people who just want to contribute a tiny fix :) I have never met PRs that I could not understand or discuss because of the lack of the information.

Please, let me know what do you think.

**Comment by nikitaeverywhere** [comment]
Haha, your PR triggered a Codacy re-ranking on the repository and now it's `C` 😃

**Comment by daguttierrez** [comment]
Hey! Yeah it is jut an starting point, I just wanted your thoughts about it, I'll start adjusting what you just mentioned and start improving the templates.

**Comment by nikitaeverywhere** [comment]
@daguttierrez, check for example [this template](https://github.com/intersystems-ru/webterminal/blob/master/issue_template.md) I created in another project. Try to keep it short and friendly if possible :)

**Comment by nikitaeverywhere** [comment]
I am closing this PR due to inactivity. @daguttierrez, let me decide this time about templates by myself. I know you try to do good things but usually templates are something the owners of the repository decide to add theirselves (like project description, etc).

**Pull request closed without merging**
